"""
Configuration package for Vivum RAG Backend
"""
from .settings import (
    SUPABASE_URL, SUPABASE_KEY, TOGETHER_API_KEY, LLM_MODEL,
    LLM_TEMPERATURE, LLM_MAX_TOKENS, EMBEDDING_MODEL,
    CLEANUP_INTERVAL_HOURS, CLEANUP_DAYS_OLD, MAX_CONVERSATIONS, PORT,
    logger
)

__all__ = [
    'SUPABASE_URL', 'SUPABASE_KEY', 'TOGETHER_API_KEY', 'LLM_MODEL',
    'LLM_TEMPERATURE', 'LLM_MAX_TOKENS', 'EMBEDDING_MODEL',
    'CLEANUP_INTERVAL_HOURS', 'CLEANUP_DAYS_OLD', 'MAX_CONVERSATIONS', 'PORT',
    'logger'
]